version: "3.8"

services:
  init-priv-validator-state:
    image: busybox
    restart: "no"
    command: [ "sh", "/home/pocket/.poktroll/scripts/init-poktrolld.sh" ]
    environment:
      - NETWORK_NAME=${NETWORK_NAME}
    volumes:
      - ./poktrolld-data:/home/pocket/.poktroll/
      - ./scripts/:/home/pocket/.poktroll/scripts
      
      # Necessary to change ownership of the files, as our production image does not run the process under root.
      - ./relayminer-example:/home/pocket/.poktroll/relayminer-example
      - ./appgate-server-example:/home/pocket/.poktroll/appgate-server-example

  # Full node
  poktrolld:
    container_name: full_node
    image: ${POKTROLLD_IMAGE_REPO}:${POKTROLLD_IMAGE_TAG:-latest}
    pull_policy: always
    entrypoint: [
      "poktrolld",
      "start",
      "--p2p.external-address=${NODE_HOSTNAME}:26656",
      "--log_level=${POKTROLLD_LOG_LEVEL}",
      "--p2p.seeds=${SEEDS}"
    ]
    ports:
      - "26657:26657"
      - "26656:26656"
    restart: unless-stopped
    depends_on:
      init-priv-validator-state:
        condition: service_completed_successfully
    volumes:
      - ./poktrolld-data:/home/pocket/.poktroll/
      - ./stake_configs:/poktroll/stake_configs

  # Relay Miner
  relayminer-example:
    image: ${POKTROLLD_IMAGE_REPO}:${POKTROLLD_IMAGE_TAG:-latest}
    container_name: relay_miner
    pull_policy: always
    entrypoint: ["sh", "/home/pocket/start-relayminer.sh"]
    environment:
      - SUPPLIER_MNEMONIC=${SUPPLIER_MNEMONIC}
    ports:
      - "8545:8545" # 8545 is the port RelayMiner is configured to listen on in `relayminer_config.yaml`.
    restart: unless-stopped
    depends_on:
      - poktrolld
    volumes:
      - ./relayminer-example:/home/pocket/.poktroll/
      - ./scripts/start-relayminer.sh:/home/pocket/start-relayminer.sh

  # AppGate Server
  appgate-server-example:
    image: ${POKTROLLD_IMAGE_REPO}:${POKTROLLD_IMAGE_TAG:-latest}
    container_name: appgate_server
    pull_policy: always
    entrypoint: ["sh", "/home/pocket/start-appgate-server.sh"]
    environment:
      - APPLICATION_MNEMONIC=${APPLICATION_MNEMONIC}
    ports:
      - "85:85" # 85 is the port AppGate Server is configured to listen on in `relayminer_config.yaml`.
    restart: unless-stopped
    depends_on:
      - poktrolld
    volumes:
      - ./appgate-server-example:/home/pocket/.poktroll/
      - ./scripts/start-appgate-server.sh:/home/pocket/start-appgate-server.sh
