version: "3.8"

services:
  init-priv-validator-state:
    image: busybox
    restart: "no"
    command:
      [
        "sh",
        "-c",
        'mkdir -p /root/.poktroll/data/; if [ ! -f /root/.poktroll/data/priv_validator_state.json ]; then echo "{\"height\": \"0\", \"round\": 0, \"step\": 0}" > /root/.poktroll/data/priv_validator_state.json; fi; chmod -R 777 /root/.poktroll/data/',
      ]
    volumes:
      - ./poktrolld-data:/root/.poktroll/

  # Full node
  poktrolld:
    container_name: full_node
    image: ${POKTROLLD_IMAGE_REPO}:${POKTROLLD_IMAGE_TAG:-main}
    pull_policy: always
    # platform: "linux/amd64" # for aarch64
    entrypoint: ["sh", "-c", "/root/start-poktrolld.sh"]
    environment:
      - P2P_NETWORK=${P2P_NETWORK}
    ports:
      - "26657:26657"
      - "26658:26658"
      - "26659:26659"
    restart: unless-stopped
    depends_on:
      init-priv-validator-state:
        condition: service_completed_successfully
    volumes:
      - ./poktrolld-data:/root/.poktroll/
      - ./stake_configs:/poktroll/stake_configs
      - ./scripts/start-poktrolld.sh:/root/start-poktrolld.sh

  # Relay Miner
  relayminer-example:
    image: ${POKTROLLD_IMAGE_REPO}:${POKTROLLD_IMAGE_TAG:-main}
    container_name: relay_miner
    pull_policy: always
    entrypoint: ["sh", "-c", "/root/start-relayminer.sh"]
    environment:
      - SUPPLIER_MNEMONIC=${SUPPLIER_MNEMONIC}
    ports:
      - "8545:8545" # 8545 is the port RelayMiner is configured to listen on in `relayminer_config.yaml`.
    restart: unless-stopped
    depends_on:
      - poktrolld
    volumes:
      - ./relayminer-example:/root/.poktroll/
      - ./scripts/start-relayminer.sh:/root/start-relayminer.sh

  # AppGate Server
  appgate-server-example:
    image: ${POKTROLLD_IMAGE_REPO}:${POKTROLLD_IMAGE_TAG:-main}
    container_name: appgate_server
    pull_policy: always
    entrypoint: ["sh", "-c", "/root/start-appgate-server.sh"]
    environment:
      - APPLICATION_MNEMONIC=${APPLICATION_MNEMONIC}
    ports:
      - "85:85" # 85 is the port AppGate Server is configured to listen on in `relayminer_config.yaml`.
    restart: unless-stopped
    depends_on:
      - poktrolld
    volumes:
      - ./appgate-server-example:/root/.poktroll/
      - ./scripts/start-appgate-server.sh:/root/start-appgate-server.sh
