global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'relay-miner'
    scheme: http
    static_configs:
      - targets: ['relayminer-example:9090']

  - job_name: 'appgate-server'
    scheme: http
    static_configs:
      - targets: ['appgate-server-example:9090']

  - job_name: 'gateway'
    scheme: http
    static_configs:
      - targets: ['gateway-example:9090']

  - job_name: 'poktrolld'
    scheme: http
    metrics_path: /metrics
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['poktrolld:1317']